# Generated by Django 4.2.8 on 2023-12-11 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumbs')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('AVENTURA', 'Aventura'), ('ANIMACAO', 'Animação'), ('ACAO', 'Ação'), ('COMEDIA', 'Comédia'), ('DRAMA', 'Drama'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('HISTORICO', 'Histórico'), ('CRIME', 'Crime'), ('FINANCAS', 'Finanças'), ('MARKETING', 'Marketing'), ('DOCUMENTARIO', 'Documentário'), ('MUSICAL', 'Musical')], max_length=15)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumbs')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('AVENTURA', 'Aventura'), ('ANIMACAO', 'Animação'), ('ACAO', 'Ação'), ('COMEDIA', 'Comédia'), ('DRAMA', 'Drama'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('HISTORICO', 'Histórico'), ('CRIME', 'Crime'), ('FINANCAS', 'Finanças'), ('MARKETING', 'Marketing'), ('DOCUMENTARIO', 'Documentário'), ('MUSICAL', 'Musical')], max_length=15)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
